; =============================================================================
; PlatformIO Konfiguration - DHT22 Pixelboard ESP32
; =============================================================================

[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

; --- Serieller Monitor -------------------------------------------------------
monitor_speed = 115200

; --- Bibliotheken (werden automatisch heruntergeladen) -----------------------
lib_deps =
    https://github.com/FastLED/FastLED.git
    https://github.com/adafruit/DHT-sensor-library.git
    https://github.com/adafruit/Adafruit_Sensor.git

; --- Verhindert dass PlatformIO Libraries als "unused" entfernt --------------
lib_ldf_mode = deep+
